apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgBvZuJS2d1H0EaMEpaEsuxWFvFyFoBgVqq4dGm9fOzin9lnli0zhd/rpQIc6UYi0tNH+1UgjQlhA0TOz66A037NGrnDiJL4+x210LcAEaRQA26LAx1yDZCQhaylONvoVmJg8r3z3+AWLU+jeOHNfToyf1sFkVQ4eeCNGAQRJhsYtxVuAPZOy02mWPpyWOKbvYS9wcld/HOe0sUHDE0vU/kMy6vYaUv2Dvq304owJzyKApiG0lJGM5XfaIcyWne2Yis0bjhK5T+jgrYrXv/1DQWK8hsLLbMNzVJJdlqii9DC/QgPzc74K0A6lVtpfsNlvQOjCCqM73muvWQHyK5SXSgG6RbGISx6XafgkaVubQgFcSX7GzGNaBc1G9uV/WwaLJmynb7aiZztpaFIgh6juCBS8lqg7bijPUj1KdVTTVzu29zNDcb/fTJuPCKc5mKrR1wnoO1ZsLEAOvlsM7fs7bfVwgj92wIJxw5A2/NQuCQK6+eFlUZSWz7rf4lzCC+81e57ORKX7/7BGcVbu/eRtFD/yhSdvYUIuLVmTOya1ONxeQLSUSq3+242sPrv5pR8Qe2ns8ex52pcpS2WASid5dG2kM49ABZIMPJZ8zErFx82DxVygR0Kmz/qNG0HxS0U/7tre05scAngv51P5IH+cPbXo2TGqlEOlJGtv9UrkuBrP229W1G9HZ3hxMN6G15L1PlJA07OxNm+DNbwSkILk4XkSctlWkZzB9WREWtg+bjH9/8=
    password: AgCNDHb9cy67KS3bqQtWSntSIx0x13CQ0qYftM+rT2UdbAdBy6u2FHGL9z4bXcgY2LWXODLsAPExFFanzhPcl8LDAKMsWvOsW7fGOtYSv5qYnBwUbK3a79+PJjdaQLhRI9f85jqnourgT1sqroPQC82boTqdPsr6tetUJzOANDEyc+3xmSblOOa9KJOjvT0hg19p1lUqoKutcHw4TLOz0TKOBD2feNgN0S6hSI4DyXDD1QWmsaH3cjYFsb1y2DyGU9AXPTZp9mdgO8a9qMf4pSFNw6kca/6qpdKbSkPyeVP/PHYM3vkU8VUk9UjEN0OpaS3CRouOxlaIGLz9MkzEu9Zy6PDKOog7LrrCnUKTK7sjcWQlWXj9/Sk5fDDPVLHG45Fnjpzhv6b2L7cJUzzeldYORX3E06GozAdEx8gmm1h9ZFt+yQjaKEv3O7EtjYKW82zvFh0nimeoIM3FXvzFGxff3WpQ7MrsIgVH5ZV1pW7gXTJXmd+jzFGo/ooZeb4HjJYcXaRR6xQcmZJaqWyHbqPZx1syfnJkbWsZO8e+fINHK7Ax/om3n/rabZpoGJyb1kK0EXDug+ha7edBABhddCpSreIU0gU098ZM8Y1WXhxtpSWb/wtaj86e5Iq3k+oCqH8nfLuVdvoNB/seg0Q69X+IR6IhBX006g2iLmui3NdKwAnDhm5Rqf4+712M2dPXL4nxvy5lClBX7Av6MS+kszY=
    username: AgAJr8aLs1Ah68rmLfHBvsHxaT9+4VqqCmg8ylA767X1Va/muP0HYrMxmdDIDsK8K0EWIYmaU+Kor4854MP9vyhNGvYDr1Pzz1wVV6AJHVb1/bjPeHdp1peSbF4dEShJemesJr3bmGzJyNn47xcx8qQAd8waQASZaXtdOfaYY15w6666+mBAGaIsmZEn1Vlx0RyvB9CUnTPHsmvLHIEQ4tDAjejHn/JcZPAQaaUSZS2M77VEcoMy7JFC1dCME8Bi6tiXwEPfVVeAzEMAlu0cgdH9d2THGSxwDLNrCt7zLgqCwFQOwosnoEskac/+wXTtLCYPFEM06jw7XgKNeu6nk4Tg1YXNVuXHQWMu8wKCrcEzBuMxxIe9gawSbACKEGy6vOp0L6zE9nQxnL9DFiGqHXguKIMuUEzYAkdNhWrdJPy1IZFFSdwZr2APpeiLYqz1cazQedVrt8JcV9OoAYAAfrQY6aIfSNv95R6mhVA0Wqm9g2WSWHLPp5faB12KdaHYQ3Bjbc/VCcfF5HVq5v1NdRfBdwcr85AV7PhZxzZDHIfZR3PMUXBUCAq7zaapGIOkfms2rX1ODIBkvpRdN5Bc9VyMCZvraxjfVowtmho1JcuR6aQSZzDcNpJC9ajUzdyYjMBAipB63VMmUv26YWnaSVj1X6E2GhnF8TsvEGbIQTQMZqwIW++vXNMMX7AfnjD7EtNWjX0tWoO++iQ/FQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque



